"""Docker deployment exporter for PAW-Kit adapters."""

from pathlib import Path
import shutil
from typing import Union


DOCKERFILE_TEMPLATE = """# Generated by PAW-Kit Docker Exporter
FROM python:3.12-slim

# Set environment variables
ENV PYTHONUNBUFFERED=1 \\
    PYTHONDONTWRITEBYTECODE=1 \\
    PORT=8000 \\
    HOST=0.0.0.0

WORKDIR /app

# Install uv package manager
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Install paw-kit and serving runtime
RUN uv pip install --system paw-kit fastapi uvicorn httpx

# Copy adapter artifact into container
COPY {adapter_filename} /app/{adapter_filename}

# Expose HTTP service port
EXPOSE 8000

# Health check
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \\
    CMD python3 -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')" || exit 1

# Launch microservice
CMD ["paw-serve", "/app/{adapter_filename}", "--host", "0.0.0.0", "--port", "8000"]
"""

DOCKERIGNORE_TEMPLATE = """__pycache__
*.pyc
*.pyo
*.pyd
.Python
env/
venv/
.venv/
.git/
.gitignore
.pytest_cache/
.coverage
dist/
build/
"""

COMPOSE_TEMPLATE = """# Generated by PAW-Kit Docker Exporter
version: '3.8'

services:
  paw-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 5s
      retries: 3
"""

README_DOCKER_TEMPLATE = """# PAW Adapter Container Deployment

This directory contains containerization assets for `{adapter_filename}`.

## Quickstart

### Build Image
```bash
docker build -t paw-adapter:{tag} .
```

### Run Container
```bash
docker run -p 8000:8000 paw-adapter:{tag}
```

### Or Run via Docker Compose
```bash
docker compose up --build -d
```

### Test Serving Endpoints

**OpenAI Client:**
```bash
curl -X POST http://localhost:8000/v1/chat/completions \\
  -H "Content-Type: application/json" \\
  -d '{{"messages": [{{"role": "user", "content": "Sample query"}}]}}'
```

**Anthropic Client:**
```bash
curl -X POST http://localhost:8000/v1/messages \\
  -H "Content-Type: application/json" \\
  -d '{{"messages": [{{"role": "user", "content": "Sample query"}}]}}'
```

**Health Check:**
```bash
curl http://localhost:8000/health
```
"""


def export_docker_scaffold(
    adapter_path: Union[str, Path],
    output_dir: Union[str, Path] = "./docker",
    copy_adapter: bool = True,
) -> Path:
    """Generate production Dockerfile and compose assets for deploying a .paw adapter."""
    adapter = Path(adapter_path)
    if not adapter.exists():
        raise FileNotFoundError(f"Adapter file '{adapter_path}' does not exist.")

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    adapter_name = adapter.name
    tag_name = adapter.stem.lower().replace("_", "-")

    # 1. Write Dockerfile
    dockerfile_content = DOCKERFILE_TEMPLATE.format(adapter_filename=adapter_name)
    (out / "Dockerfile").write_text(dockerfile_content, encoding="utf-8")

    # 2. Write .dockerignore
    (out / ".dockerignore").write_text(DOCKERIGNORE_TEMPLATE, encoding="utf-8")

    # 3. Write docker-compose.yml
    (out / "docker-compose.yml").write_text(COMPOSE_TEMPLATE, encoding="utf-8")

    # 4. Write README.md
    readme_content = README_DOCKER_TEMPLATE.format(
        adapter_filename=adapter_name,
        tag=tag_name,
    )
    (out / "README.md").write_text(readme_content, encoding="utf-8")

    # 5. Copy adapter file
    if copy_adapter:
        dest_adapter = out / adapter_name
        if adapter.resolve() != dest_adapter.resolve():
            shutil.copy2(adapter, dest_adapter)

    return out
