"""Docker deployment exporter for PAW-Kit adapters."""

from pathlib import Path
import re
import shutil
from typing import Union

# PAW-DOCKER-01: the exact set of filenames export_docker_scaffold writes into
# output_dir itself. An adapter_name colliding with one of these lets a crafted
# adapter path (e.g. "./Dockerfile") overwrite a just-generated deployment file via
# the copy-adapter step below.
_RESERVED_OUTPUT_FILENAMES = frozenset({"Dockerfile", ".dockerignore", "docker-compose.yml", "README.md"})


DOCKERFILE_TEMPLATE = """# Generated by PAW-Kit Docker Exporter
FROM python:3.12-slim

# Set environment variables
ENV PYTHONUNBUFFERED=1 \\
    PYTHONDONTWRITEBYTECODE=1 \\
    PORT=8000

# PAW-SERVE-01: no default API key is baked into the image (that would leak a
# secret into every image layer/registry). Supply one at *runtime* instead, e.g.:
#   docker run -e PAW_API_KEY=<your-secret> ...
# paw-serve already reads PAW_API_KEY from the process environment; if it is
# absent, the container falls back to generating and logging an ephemeral token
# (see `docker logs`) rather than serving anonymously.

WORKDIR /app

# Install uv package manager
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Install paw-kit and serving runtime
RUN uv pip install --system paw-kit fastapi uvicorn httpx

# Create unprivileged application user
RUN addgroup --system app && adduser --system --ingroup app app

# Copy adapter artifact into container
COPY --chown=app:app {adapter_filename} /app/{adapter_filename}

USER app

# Expose HTTP service port
EXPOSE 8000

# Health check (unauthenticated: /health does not require PAW_API_KEY)
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \\
    CMD python3 -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')" || exit 1

# Launch microservice. PAW_API_KEY, if set in the container's environment, is
# picked up automatically by paw-serve; no CLI flag is needed here for it.
CMD ["paw-serve", "/app/{adapter_filename}", "--host", "0.0.0.0", "--port", "8000"]
"""

DOCKERIGNORE_TEMPLATE = """__pycache__
*.pyc
*.pyo
*.pyd
.Python
env/
venv/
.venv/
.git/
.gitignore
.pytest_cache/
.coverage
dist/
build/
"""

COMPOSE_TEMPLATE = """# Generated by PAW-Kit Docker Exporter
version: '3.8'

services:
  paw-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      # PAW-SERVE-01: forwards the host's PAW_API_KEY into the container so the
      # generated container inherits auth-by-default instead of a freshly minted
      # ephemeral token on every restart. Set it before running `docker compose up`,
      # e.g. `export PAW_API_KEY=$(openssl rand -base64 32)`, or add it to a `.env`
      # file next to this compose file. Leaving it unset falls back to an ephemeral
      # token logged to `docker compose logs`, not anonymous access.
      - PAW_API_KEY=${PAW_API_KEY:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 5s
      retries: 3
"""

README_DOCKER_TEMPLATE = """# PAW Adapter Container Deployment

This directory contains containerization assets for `{adapter_filename}`.

## Authentication (PAW-SERVE-01)

The server authenticates by default. Set `PAW_API_KEY` before starting the container,
or it will generate and log a new ephemeral bearer token on every start/restart
(visible via `docker logs` / `docker compose logs`, and **rotating on every restart**
— clients holding the old token will start getting 401s). To use a stable key:

```bash
export PAW_API_KEY=$(openssl rand -base64 32)
```

### Build Image
```bash
docker build -t paw-adapter:{tag} .
```

### Run Container
```bash
docker run -p 8000:8000 -e PAW_API_KEY="$PAW_API_KEY" paw-adapter:{tag}
```

### Or Run via Docker Compose
```bash
docker compose up --build -d
```
(`docker-compose.yml` forwards `PAW_API_KEY` from your shell automatically — see its
`environment:` block.)

### Test Serving Endpoints

**OpenAI Client:**
```bash
curl -X POST http://localhost:8000/v1/chat/completions \\
  -H "Content-Type: application/json" \\
  -H "Authorization: Bearer $PAW_API_KEY" \\
  -d '{{"messages": [{{"role": "user", "content": "Sample query"}}]}}'
```

**Anthropic Client:**
```bash
curl -X POST http://localhost:8000/v1/messages \\
  -H "Content-Type: application/json" \\
  -H "Authorization: Bearer $PAW_API_KEY" \\
  -d '{{"messages": [{{"role": "user", "content": "Sample query"}}]}}'
```

**Health Check** (unauthenticated by design):
```bash
curl http://localhost:8000/health
```
"""


def export_docker_scaffold(
    adapter_path: Union[str, Path],
    output_dir: Union[str, Path] = "./docker",
    copy_adapter: bool = True,
) -> Path:
    """Generate production Dockerfile and compose assets for deploying a .paw adapter."""
    adapter = Path(adapter_path)
    if not adapter.exists():
        raise FileNotFoundError(f"Adapter file '{adapter_path}' does not exist.")

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    adapter_name = adapter.name

    if not re.match(r"^[\w\-.]+$", adapter_name):
        raise ValueError(f"Adapter filename contains unsafe characters: {adapter_name!r}")

    # PAW-DOCKER-01: `adapter.name` is a Path.name and can never contain a path
    # separator, so a traversal sequence cannot reach this point — the real,
    # verified vector is an adapter filename that collides with one of the four
    # files this function writes below, letting the "copy adapter" step overwrite
    # a just-generated deployment file (e.g. `paw export docker ./Dockerfile
    # --out-dir ./deploy` would otherwise overwrite the generated Dockerfile).
    if adapter_name in _RESERVED_OUTPUT_FILENAMES:
        raise ValueError(
            f"Adapter filename {adapter_name!r} collides with a file "
            f"export_docker_scaffold generates itself {sorted(_RESERVED_OUTPUT_FILENAMES)}; "
            "rename the adapter file."
        )
    if not adapter_name.endswith(".paw"):
        raise ValueError(f"Adapter filename must have a '.paw' extension: {adapter_name!r}")

    tag_name = adapter.stem.lower().replace("_", "-")

    # 1. Write Dockerfile
    dockerfile_content = DOCKERFILE_TEMPLATE.format(adapter_filename=adapter_name)
    (out / "Dockerfile").write_text(dockerfile_content, encoding="utf-8")

    # 2. Write .dockerignore
    (out / ".dockerignore").write_text(DOCKERIGNORE_TEMPLATE, encoding="utf-8")

    # 3. Write docker-compose.yml
    (out / "docker-compose.yml").write_text(COMPOSE_TEMPLATE, encoding="utf-8")

    # 4. Write README.md
    readme_content = README_DOCKER_TEMPLATE.format(
        adapter_filename=adapter_name,
        tag=tag_name,
    )
    (out / "README.md").write_text(readme_content, encoding="utf-8")

    # 5. Copy adapter file
    if copy_adapter:
        dest_adapter = out / adapter_name
        if adapter.resolve() != dest_adapter.resolve():
            shutil.copy2(adapter, dest_adapter)

    return out
