"""Docker deployment exporter for PAW-Kit adapters."""

from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _pkg_version
from pathlib import Path
import re
import shutil
from typing import Union

# PAW-DOCKER-01: the exact set of filenames export_docker_scaffold writes into
# output_dir itself. An adapter_name colliding with one of these lets a crafted
# adapter path (e.g. "./Dockerfile") overwrite a just-generated deployment file via
# the copy-adapter step below. requirements.txt (PAW-DOCKER-03) is a generated file
# too, so it must be reserved the same way as the other four.
_RESERVED_OUTPUT_FILENAMES = frozenset(
    {"Dockerfile", ".dockerignore", "docker-compose.yml", "README.md", "requirements.txt"}
)

# PAW-DEPS-01's floors: the lowest version each dependency is declared compatible
# with in pyproject.toml, used only if this environment's installed metadata can't
# be read (e.g. an unusual install layout) — so a generated requirements.txt is
# always pinned to *something* concrete rather than silently falling back to an
# unpinned line.
_REQUIREMENT_FALLBACK_VERSIONS = {
    "paw-kit": "0.1.0",
    "fastapi": "0.110.0",
    "uvicorn": "0.28.0",
    "httpx": "0.27.0",
}


def _pinned_requirement(package: str) -> str:
    """PAW-DOCKER-03: pin to the exact version installed in *this* environment — the
    one that actually compiled/exported the adapter — rather than an unpinned bare
    package name that lets every future container build resolve a different,
    untested dependency set on its own schedule."""
    try:
        resolved = _pkg_version(package)
    except PackageNotFoundError:
        resolved = _REQUIREMENT_FALLBACK_VERSIONS[package]
    return f"{package}=={resolved}"


DOCKERFILE_TEMPLATE = """# Generated by PAW-Kit Docker Exporter
FROM python:3.12-slim

# Set environment variables
ENV PYTHONUNBUFFERED=1 \\
    PYTHONDONTWRITEBYTECODE=1 \\
    PORT=8000

# PAW-SERVE-01: no default API key is baked into the image (that would leak a
# secret into every image layer/registry). Supply one at *runtime* instead, e.g.:
#   docker run -e PAW_API_KEY=<your-secret> ...
# paw-serve already reads PAW_API_KEY from the process environment; if it is
# absent, the container falls back to generating and logging an ephemeral token
# (see `docker logs`) rather than serving anonymously.

WORKDIR /app

# Install uv package manager
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# PAW-DOCKER-03: install from a generated, pinned requirements.txt (exact versions,
# pulled from the environment that ran the exporter) instead of an unpinned inline
# package list, so every image build resolves the same dependency set rather than
# whatever happens to be latest on PyPI that day.
COPY requirements.txt /app/requirements.txt
RUN uv pip install --system -r requirements.txt

# Create unprivileged application user
RUN addgroup --system app && adduser --system --ingroup app app

# Copy adapter artifact into container
COPY --chown=app:app {adapter_filename} /app/{adapter_filename}

USER app

# Expose HTTP service port
EXPOSE 8000

# Health check (unauthenticated: /ready does not require PAW_API_KEY). Checks
# readiness, not just liveness: /health returns ok before any model is loaded, so a
# container could report "healthy" while its single inference slot is still busy with
# the cold model load. --start-period covers a first-run cold download of the ~600MB
# base model plus load, measured up to ~110s worst case (see measurements/README.md);
# 180s leaves headroom above that measurement rather than matching it exactly.
HEALTHCHECK --interval=30s --timeout=5s --start-period=180s --retries=3 \\
    CMD python3 -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/ready')" || exit 1

# Launch microservice. PAW_API_KEY, if set in the container's environment, is
# picked up automatically by paw-serve; no CLI flag is needed here for it. --warm pays
# the cold-load cost (base model download + load into memory) before the container
# reports ready, instead of on whatever request happens to arrive first.
CMD ["paw-serve", "/app/{adapter_filename}", "--host", "0.0.0.0", "--port", "8000", "--warm"]
"""

def _requirements_txt_content() -> str:
    """Render requirements.txt content, pinned per `_pinned_requirement`."""
    lines = ["# Generated by PAW-Kit Docker Exporter — exact versions, not ranges."]
    lines.extend(_pinned_requirement(pkg) for pkg in ("paw-kit", "fastapi", "uvicorn", "httpx"))
    return "\n".join(lines) + "\n"


DOCKERIGNORE_TEMPLATE = """__pycache__
*.pyc
*.pyo
*.pyd
.Python
env/
venv/
.venv/
.git/
.gitignore
.pytest_cache/
.coverage
dist/
build/
"""

COMPOSE_TEMPLATE = """# Generated by PAW-Kit Docker Exporter
version: '3.8'

services:
  paw-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    # PAW-DOCKER-02: bind the published port to loopback only by default. The
    # container's own internal bind stays 0.0.0.0 (required for Docker's networking
    # to reach it at all) — this only controls which *host* interfaces the mapped
    # port is reachable from. Change to "8000:8000" only if external/LAN access is
    # actually intended, ideally behind a reverse proxy that terminates TLS.
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      # PAW-SERVE-01: forwards the host's PAW_API_KEY into the container so the
      # generated container inherits auth-by-default instead of a freshly minted
      # ephemeral token on every restart. Set it before running `docker compose up`,
      # e.g. `export PAW_API_KEY=$(openssl rand -base64 32)`, or add it to a `.env`
      # file next to this compose file. Leaving it unset falls back to an ephemeral
      # token logged to `docker compose logs`, not anonymous access.
      - PAW_API_KEY=${PAW_API_KEY:-}
    restart: unless-stopped
    healthcheck:
      # See the matching Dockerfile HEALTHCHECK comment: /ready (readiness), not
      # /health (liveness), and a start_period that covers a cold base-model download.
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/ready')"]
      interval: 30s
      timeout: 5s
      start_period: 180s
      retries: 3
"""

README_DOCKER_TEMPLATE = """# PAW Adapter Container Deployment

This directory contains containerization assets for `{adapter_filename}`.

## Authentication (PAW-SERVE-01)

The server authenticates by default. Set `PAW_API_KEY` before starting the container,
or it will generate and log a new ephemeral bearer token on every start/restart
(visible via `docker logs` / `docker compose logs`, and **rotating on every restart**
— clients holding the old token will start getting 401s). To use a stable key:

```bash
export PAW_API_KEY=$(openssl rand -base64 32)
```

### Build Image
```bash
docker build -t paw-adapter:{tag} .
```

### Run Container
```bash
docker run -p 127.0.0.1:8000:8000 -e PAW_API_KEY="$PAW_API_KEY" paw-adapter:{tag}
```
(PAW-DOCKER-02: bound to loopback only, matching `docker-compose.yml`'s default —
swap `127.0.0.1:8000:8000` for `8000:8000` only if external/LAN access is actually
intended, ideally behind a reverse proxy that terminates TLS.)

### Or Run via Docker Compose
```bash
docker compose up --build -d
```
(`docker-compose.yml` forwards `PAW_API_KEY` from your shell automatically — see its
`environment:` block.)

### Test Serving Endpoints

**OpenAI Client:**
```bash
curl -X POST http://localhost:8000/v1/chat/completions \\
  -H "Content-Type: application/json" \\
  -H "Authorization: Bearer $PAW_API_KEY" \\
  -d '{{"messages": [{{"role": "user", "content": "Sample query"}}]}}'
```

**Anthropic Client:**
```bash
curl -X POST http://localhost:8000/v1/messages \\
  -H "Content-Type: application/json" \\
  -H "Authorization: Bearer $PAW_API_KEY" \\
  -d '{{"messages": [{{"role": "user", "content": "Sample query"}}]}}'
```

**Health Check** (unauthenticated by design): `/health` is liveness (process is up);
`/ready` is readiness (the model has actually loaded and served one successful call --
this container's HEALTHCHECK polls `/ready`, and `--warm` in its CMD pays that cold-load
cost before the container reports ready, not on whatever request happens to arrive first):
```bash
curl http://localhost:8000/health
curl http://localhost:8000/ready
```
"""


def export_docker_scaffold(
    adapter_path: Union[str, Path],
    output_dir: Union[str, Path] = "./docker",
    copy_adapter: bool = True,
) -> Path:
    """Generate production Dockerfile and compose assets for deploying a .paw adapter."""
    adapter = Path(adapter_path)
    if not adapter.exists():
        raise FileNotFoundError(f"Adapter file '{adapter_path}' does not exist.")

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    adapter_name = adapter.name

    if not re.match(r"^[\w\-.]+$", adapter_name):
        raise ValueError(f"Adapter filename contains unsafe characters: {adapter_name!r}")

    # PAW-DOCKER-01: `adapter.name` is a Path.name and can never contain a path
    # separator, so a traversal sequence cannot reach this point — the real,
    # verified vector is an adapter filename that collides with one of the four
    # files this function writes below, letting the "copy adapter" step overwrite
    # a just-generated deployment file (e.g. `paw export docker ./Dockerfile
    # --out-dir ./deploy` would otherwise overwrite the generated Dockerfile).
    if adapter_name in _RESERVED_OUTPUT_FILENAMES:
        raise ValueError(
            f"Adapter filename {adapter_name!r} collides with a file "
            f"export_docker_scaffold generates itself {sorted(_RESERVED_OUTPUT_FILENAMES)}; "
            "rename the adapter file."
        )
    if not adapter_name.endswith(".paw"):
        raise ValueError(f"Adapter filename must have a '.paw' extension: {adapter_name!r}")

    tag_name = adapter.stem.lower().replace("_", "-")

    # 1. Write Dockerfile
    dockerfile_content = DOCKERFILE_TEMPLATE.format(adapter_filename=adapter_name)
    (out / "Dockerfile").write_text(dockerfile_content, encoding="utf-8")

    # 2. Write .dockerignore
    (out / ".dockerignore").write_text(DOCKERIGNORE_TEMPLATE, encoding="utf-8")

    # 3. Write docker-compose.yml
    (out / "docker-compose.yml").write_text(COMPOSE_TEMPLATE, encoding="utf-8")

    # 4. Write README.md
    readme_content = README_DOCKER_TEMPLATE.format(
        adapter_filename=adapter_name,
        tag=tag_name,
    )
    (out / "README.md").write_text(readme_content, encoding="utf-8")

    # 5. Write requirements.txt (PAW-DOCKER-03)
    (out / "requirements.txt").write_text(_requirements_txt_content(), encoding="utf-8")

    # 6. Copy adapter file
    if copy_adapter:
        dest_adapter = out / adapter_name
        if adapter.resolve() != dest_adapter.resolve():
            shutil.copy2(adapter, dest_adapter)

    return out
